# Generated by Django 2.1.4 on 2018-12-28 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AP', 'Appetizers'), ('SA', 'Salad'), ('BF', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Soup'), ('BV', 'Beverages'), ('SP', 'Special')], max_length=20, verbose_name='Name of the dish')),
                ('description', models.TextField(max_length=300)),
                ('dish_image', models.FileField(upload_to='')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
