# Generated by Django 2.1.4 on 2018-12-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('AP', 'Appetizers'), ('SA', 'Salad'), ('BF', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Soup'), ('BV', 'Beverages'), ('SP', 'Special')], default='SP', max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name of the dish'),
        ),
    ]
