# Generated by Django 2.1.4 on 2018-12-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20181229_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dish_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
