# Generated by Django 2.1.4 on 2018-12-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20181230_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('AP', 'Appetizer'), ('SA', 'Salad'), ('BF', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Soup'), ('DS', 'Dessert'), ('SP', 'Special')], default='SP', max_length=20),
        ),
    ]
